#!/usr/bin/env python3
"""Check a body diff before sending it, using the server's own validator.

`vault_propose_note_body_diff` applies a strict unified-diff grammar: hunk
headers must be well formed, their line counts must match the lines that
follow, context must match the note byte for byte, and the whole change must
stay inside the compact-diff policy. A patch that fails any of those is
refused, and the refusal costs a round trip and a retry.

This runs the same check locally, against the same code the server runs --
`app.vault.body_diff.apply_body_unified_diff`, imported rather than
reimplemented. A second copy of the grammar would eventually disagree with the
first, and the failure mode would be this script blessing a patch the server
rejects, which is worse than no script at all.

**Prefer `vault_propose_note_span_edit` to writing a diff.** Naming the old
text and the new text needs no hunk arithmetic, and the server materializes
the canonical diff itself (ADR 0033). This script exists for a caller that
already has a diff -- generated by `git diff`, or written by hand -- and wants
to know whether it will be accepted.

Usage:

    python -m scripts.validate_body_diff --note-file body.md --diff-file change.patch
    vault_get_note ... | python -m scripts.validate_body_diff --diff-file change.patch --note-stdin

Exit status is 0 when the patch applies and 1 when it does not, so it can gate
a send in a shell pipeline.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from app.vault.body_diff import BodyDiffError, apply_body_unified_diff


def _read_note(args: argparse.Namespace) -> str:
    """The note body, from a file, or from a `vault_get_note` payload on stdin.

    Accepting the tool's JSON directly matters more than it looks: the usual
    way to get a body wrong is to copy it out of a rendered response and lose
    the trailing newline or a run of spaces, and a diff whose context differs
    from the note by one space fails every hunk for a reason the error cannot
    name.
    """

    if args.note_stdin:
        raw = sys.stdin.read()
        try:
            payload = json.loads(raw)
        except json.JSONDecodeError:
            # Not JSON, so treat the whole of stdin as the body itself.
            return raw
        if isinstance(payload, dict) and isinstance(payload.get("body"), str):
            return payload["body"]
        raise SystemExit(
            "stdin parsed as JSON but carries no 'body' string; pass the "
            "vault_get_note result, or use --note-file"
        )
    return Path(args.note_file).read_text(encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Validate a vault body diff without sending it.",
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--note-file", help="File holding the note's exact body.")
    source.add_argument(
        "--note-stdin",
        action="store_true",
        help="Read the body from stdin, or a vault_get_note JSON result.",
    )
    parser.add_argument("--diff-file", required=True, help="The unified diff.")
    parser.add_argument(
        "--show-result",
        action="store_true",
        help="Print the resulting body when the patch applies.",
    )
    args = parser.parse_args(argv)

    body = _read_note(args)
    patch = Path(args.diff_file).read_text(encoding="utf-8")

    try:
        result = apply_body_unified_diff(body, patch)
    except BodyDiffError as exc:
        print(f"REJECTED: {exc}", file=sys.stderr)
        print(
            "\nThe server applies this same check and will refuse the same "
            "patch.\nConsider vault_propose_note_span_edit instead: name the "
            "old text and\nthe new text, and the server writes the diff.",
            file=sys.stderr,
        )
        return 1

    removed = len(result.removed_lines)
    print(
        f"OK: {result.hunk_count} hunk(s), "
        f"+{result.added_line_count} line(s), -{removed} line(s)"
    )
    if removed:
        # Worth surfacing before sending: a proposal that removes lines needs
        # `acknowledge_removals` at decision time (ADR 0028), so a caller who
        # did not intend a deletion should find out here.
        print("  removes:")
        for line in result.removed_lines:
            print(f"    {line.line_number}: {line.text}")
    if args.show_result:
        print("\n--- resulting body ---")
        print(result.body, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
